### ISSUE TITLE
64 bit Pharo VM on Mac hangs on full screen

### ISSUE THREAD

**Issue by StephanEggermont** [OpenSmalltalk/opensmalltalk-vm#380]
64 bit Pharo VM Version from 2019-1-5, Squeak VM version from 2018-12-14 
Images Pharo 8 build 136 and Squeak 5.2 18229

Switching to full screen using the Pharo VM hangs, using the Squeak VM works for both images

https://github.com/pharo-project/pharo/issues/2343

**Comment by StephanEggermont** [comment]
And it is a regression. With the PharoLauncher VM I have here for Pharo6.1 from 2018-6-28 5.0.201806281256 I can not reproduce

**Comment by eliotmiranda** [comment]
Hi Stephan, on Squeak with two monitors, while I don't see the Vm lock up (one can still see the clock ticking in the menu bar), I do see the image become completely unresponsive to mouse input.  So I see a serious problem with the latest Squeak VM too (I tested a 64-bit system on a home built VM derived from Croquet Closure Cog[Spur] VM [CoInterpreterPrimitives VMMaker.oscog-eem.2530] 5.0.201902020720, with older platform code, avoiding Ronie's latest Metal shader code which doesn't compile on my 10.13.6 MPB).

**Comment by StephanEggermont** [comment]
201810222239 works, 201810230536 is broken

**Comment by StephanEggermont** [comment]
So it looks like it is 

https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/671517e30e5afd50d75b90d1a64cb89add6b678c
https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/94e4f2565db5f75f1c0a9268eb2288d69f5cc58f
https://github.com/OpenSmalltalk/opensmalltalk-vm/commit/9320885e03ad028ec2da8c1f1cc6cddcc83045b1

**Comment by StephanEggermont** [comment]
The primitive is not enough. doIt DisplayScreen toggleFullscreen. and see fullScreen:

**Comment by StephanEggermont** [comment]
Where do I find the build artefacts?

**Comment by StephanEggermont** [comment]
Should that be fixed in pharo.cog.spur_macos64x64_201903251926?. I still manage to get an unresponsive Pharo image when doing in a playground: Display toggleFullscreen

**Comment by eliotmiranda** [comment]
Looks like we still have an issue.  I did my testing in a two screen configuration and it worked there.  But we've just tried on a one screen laptop and indeed the system stops delivering events into the system wen we switch to full screen.  So it looks like the issue has yet to be fixed.

**Comment by johnmci** [comment]
I had a comment in #381 Didn’t understand if the change did the right thing. Also is this random failure or always happens with a chunk of smalltalk I can run?

**Comment by StephanEggermont** [comment]
Always happens. It might be Mac OS version dependent. On 10.14.3 without an external monitor connected on my MBP I can reliably reproduce it in a Pharo 7 or 8 by opening a playground and doing 

Display toggleFullscreen. 

On Squeak I used 

Display fullScreenMode: true. Display newDepth: Display depth
